### ISSUE TITLE
Configurações do projeto

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [kaway404/Netflix#11]
Primeiramente, parabéns pelo projeto, estou com uma dúvida, quando você diz: "E adicione a .sql na db" o que exatamente seria isso? Eu modifiquei o arquivo config no caminho static\php\system, mas estou recebendo erro 404: Not Found
The requested URL /account.php was not found on this server.
Poderia me ajudar?

**Comment by kaway404** [comment]
A versão do php tem que ser 5.6, e vê se teu servidor tem suporte para .htaccess

**Comment by andersonvieiragomeslopes** [comment]
Alterei agora a versão do php, e tem suporte ao .htaccess, mesmo assim permanece o mesmo erro: http://andersonvieira2.hol.es/Netflix/account

**Comment by kaway404** [comment]
Tenta tirar a pasta /netflix, e deixar no diretório principal

**Comment by andersonvieiragomeslopes** [comment]
Bem.. isso resolveu o problema, obrigado.
