### ISSUE TITLE
Console Floodado de Erros

### ISSUE THREAD

**Issue by IZ44KPvP** [kaway404/Netflix#4]
Quando eu acesso o player de algum vídeo, ele fica dando esse erro no console:
![erros](https://user-images.githubusercontent.com/19996738/33586810-5b832cee-d952-11e7-8516-58569fcf0cf7.png)

O erro não para de aparecer chega a ficar flodando a mais de 10000 vezes e isso acaba com a memoria ram do PC

**Comment by IZ44KPvP** [comment]
Acabei de ver os commits e vi que foi resolvido, desculpe.

**Comment by IZ44KPvP** [comment]
Pelo que eu vi acaba mexida no mouse aparece mais erros.

**Comment by kaway404** [comment]
Obrigado por me informar o erro

**Comment by IZ44KPvP** [comment]
Por nada
